# Generated by Django 4.2.3 on 2023-10-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_user_email_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="userid",
            field=models.UUIDField(
                auto_created=True, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
